### ISSUE TITLE
help to integrate mercadopago plugin

### ISSUE THREAD

**Issue by ralexale** [minskylab/medusa-payment-mercadopago#3]
hello i am trying to integrate the mercado pago plugin to the storefront but i have problems to get the checkout button, when i press the mercado pago option nothing happens and i get the following error

![image](https://github.com/minskylab/medusa-payment-mercadopago/assets/59479109/b2252413-9492-40b3-8481-7fd8a89413e9)

if someone could help me I would be very grateful because this is the only payment method for latin america.

**Comment by Machi3mfl** [comment]
@ralexale Have you been able to solve this? I have the same issue.

**Comment by ralexale** [comment]
@Machi3mfl yes in the folder @minskylab/medusa-payment-mercadopago/dist/services/mercadopago.js

go to the "createPayment" key and change the payer data in preferences

![mercado pago1](https://github.com/minskylab/medusa-payment-mercadopago/assets/59479109/a56206be-be99-451f-8bfb-6e8c77ace75d)

also if it does not detect the .env you can pass them,
make sure that the back_url is https otherwise MercadoPago will reject the transaction.  


![notification](https://github.com/minskylab/medusa-payment-mercadopago/assets/59479109/a35569cb-ad30-40b9-ba3e-520bca61afb0)
